wandb_version: 1

max_steps:
  desc: null
  value: 100
model:
  desc: null
  value: SRDiff
learning_rate:
  desc: null
  value: 0.0002
decay_steps:
  desc: null
  value: 100000
gamma:
  desc: null
  value: 0.5
batch_size:
  desc: null
  value: 16
hidden_size:
  desc: null
  value: 64
dim_mults:
  desc: null
  value:
  - 1
  - 2
  - 2
  - 4
rrdb_num_features:
  desc: null
  value: 32
rrdb_num_blocks:
  desc: null
  value: 8
loss_type:
  desc: null
  value: l1
_wandb:
  desc: null
  value:
    python_version: 3.12.2
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1713714641.0
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.12.2
      5: 0.16.5
      8:
      - 1
      - 3
      - 5
      13: windows-amd64
